package by.epam.movierating.command;

/**
 * Created by Даша on 14.02.2017.
 */
public enum CommandName {
    LOGIN, LOGOUT, VIEW_ALL_MOVIES, VIEW_MOVIE,
    CHANGE_LANGUAGE, WELCOME_PAGE, VIEW_MOVIES_BY_GENRE,
    DELETE_MOVIE, REGISTRATION, REDIRECT,
    VIEW_ALL_USERS, VIEW_USER, VIEW_MOVIES_BY_COUNTRY, EDIT_USER,
    CHANGE_BAN_STATUS, DELETE_USER, EDIT_MOVIE
}