package by.epam.movierating.command;

/**
 * Created by Даша on 14.02.2017.
 */
public enum CommandName {
    LOGIN, LOGOUT, VIEW_ALL_MOVIES, VIEW_MOVIE,
    CHANGE_LANGUAGE, WELCOME_PAGE, VIEW_MOVIES_BY_GENRE,
    DELETE_MOVIE, REGISTRATION, REDIRECT,
    VIEW_ALL_USERS, VIEW_USER, VIEW_MOVIES_BY_COUNTRY, EDIT_USER,
    CHANGE_BAN_STATUS, DELETE_USER, EDIT_MOVIE, DELETE_GENRE_FOR_MOVIE,
    VIEW_GENRES_NOT_IN_MOVIE, ADD_GENRE_FOR_MOVIE,
    VIEW_MOVIES_BY_GENRE_NAME, VIEW_MOVIES_BY_COUNTRY_NAME,
    VIEW_MOVIES_BY_ACTOR_INITIAL, DELETE_COUNTRY_FOR_MOVIE,
    VIEW_COUNTRIES_NOT_IN_MOVIE, ADD_COUNTRY_FOR_MOVIE,
    DELETE_ACTOR_FOR_MOVIE, ADD_ACTOR_FOR_MOVIE,
    VIEW_ACTORS_NOT_IN_MOVIE, ADD_MOVIE, VIEW_ALL_GENRES,
    VIEW_ALL_COUNTRIES, VIEW_ALL_ACTORS_JSON, VIEW_ALL_REVIEWS_ORDER_BY_DATE,
    VIEW_ALL_ACTORS, VIEW_TOP_MOVIES, DELETE_ACTOR,
    EDIT_ACTOR,ADD_ACTOR, VIEW_NEWEST_MOVIES,

    UPLOAD_ACTOR_IMAGE, UPLOAD_MOVIE_POSTER
}